spring:
  kafka:
    bootstrap-servers:
    template:
      default-topic:
    consumer:
      group-id:
  application:
    name: api-template
    description: A base template for a RESTful service
    version: "@application.version@"
    timestamp: "@application.buildTimestamp@"
    branch: "@application.branch@"
    environment: ${ENV}

#api:
#  name: ${spring.application.name}
#  description: A base template for a RESTful service
#  basePath: "api/"
#    v1: "v1"
#    v2: "v2"

server:
  port: 8080
  contextPath: /api-template

logback:
  appender: consoleColor
  level: DEBUG
